apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: go-api
  annotations:
    github.com/project-slug: cybercyst/go-api
spec:
  type: service
  lifecycle: experimental
  owner: team-a
