services:
  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 8080:80
    depends_on:
      - backend

  backend:
    container_name: go-api
    build: .
    x-develop:
      watch:
        - action: sync
          path: ./flags.yaml
          target: /app/flags.yaml
        - action: rebuild
          path: .
    env_file:
      - .env
    environment:
      ENV: ${ENV:-dev}
      PODNAME: ${PODNAME:-go-api}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      FILE_UPLOAD_BUCKET: ${FILE_UPLOAD_BUCKET:-}
