services:
  api:
    container_name: go-api
    build:
      dockerfile: Dockerfile.dev
    environment:
      ENV: dev
      PODNAME: not_in_k8s
    volumes:
      - .:/app
    ports:
      - '8080:8080'
