name: CD

concurrency:
  group: ${{ github.workflow }}

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  changes:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      run: "${{ steps.changes.outputs.code == 'true' }}"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: version
        run: |
          ver=$(git describe --abbrev=0 --match "v*.*.*")
          echo "::set-output name=version::$ver"
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          base: ${{ steps.version.outputs.version }}
          filters: |
            code:
              - Dockerfile
              - '**/*.go'
              - 'go.mod'
              - 'go.sum'

  version:
    name: Get Version
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.run == 'true' }}
    outputs:
      version: ${{ steps.version.outputs.inc-minor }}
      version_tag: v${{ steps.version.outputs.inc-minor }}
    needs:
      - changes
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: current_version
        run: |
          ver=$(git describe --abbrev=0 --match "v*.*.*")
          echo "::set-output name=version::$ver"
      - uses: madhead/semver-utils@latest
        id: version
        with:
          version: ${{ steps.current_version.outputs.version }}

  tag:
    name: Tag
    runs-on: ubuntu-latest
    needs:
      - changes
      - version
    steps:
      - uses: actions/checkout@v4
      - name: Create Tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ needs.version.outputs.version_tag }}
      - name: Rollback
        if: failure()
        run: git push --delete origin ${{ needs.version.outputs.version_tag }}

  push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs:
      - version
      - tag
    steps:
      - uses: actions/checkout@v4
      - name: Hub Login
        uses: docker/login-action@v3
        with:
          username: forrestloomis786
          password: ${{ secrets.DOCKER_HUB_PAT }}
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          target: prod
          push: true
          tags: |
            forrestloomis786/upload-api:${{ needs.version.outputs.version }}
            forrestloomis786/upload-api:latest
          labels: |
            com.docker.image.source.entrypoint=Dockerfile
      - name: Rollback
        if: failure()
        run: git push --delete origin ${{ needs.version.outputs.version_tag }}
